# Generated by Django 5.2.6 on 2025-09-12 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_remove_project_profile_picture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                through="projects.ProjectMembership",
                through_fields=("project", "member"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
